### ISSUE TITLE
expanding with large collapsed address fails

### ISSUE THREAD

**Issue by sjorge** [mutax/IPv6-Address-checks#1]
e.g. 2001:6f8:DEAD:10::1 will fail to validate

inserting: ``` ZEROES=``` above the line ```GRPS="$(sed  's|[0-9a-f]||g' <<< "$INPUT" | wc -m)``` fixed it for me.

**Comment by mutax** [comment]
ZEROES was not initialized, but when I tried to reproduce it only failed validation when I used upepr case hex digits. Fixed that by lowercasing first and initialized ZEROES. Thanks!
